config/routes.rb
Rails.application.routes.draw do
  root "matches#index"

  resources :matches, only: %i(new create index)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :match_members
  has_many :members, through: :match_members
end

app/models/match_member.rb
class MatchMember < ApplicationRecord
  belongs_to :member
end

app/models/member.rb
class Member < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV["BASIC_AUTH_USERNAME"], password: ENV["BASIC_AUTH_PASSWORD"]
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)
    member_params[:member_names].each do |name|
      @match.members.build(name: name)
    end

    if @match.save
      # TODO: 今は index に遷移しているが、本来は「1試合目の結果入力画面」
      #       に遷移する。今後対応する。
      redirect_to matches_path
    else
      render :new
    end
  end

  private

  def match_params
    params.permit(:saki)
  end

  def member_params
    params.permit(member_names: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Senseki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matches/index.html.haml
%h1 Match#index

= link_to "新しいマッチをはじめる", new_match_path

app/views/matches/new.html.haml
%h1 新しいマッチをはじめる
= form_tag matches_path do
  = select_tag :saki, options_for_select((1..10).to_a)
  = label_tag :member_1
  = text_field_tag "member_names[]", nil, { id: :member_1, required: "required" }

  = label_tag :member_2
  = text_field_tag "member_names[]", nil, { id: :member_2, required: "required" }

  = label_tag :member_3
  = text_field_tag "member_names[]", nil, { id: :member_3, required: "required" }

  = label_tag :member_4
  = text_field_tag "member_names[]", nil, { id: :member_4, required: "required" }

  = label_tag :member_5
  = text_field_tag "member_names[]", nil, { id: :member_5, required: "required" }

  = label_tag :member_6
  = text_field_tag "member_names[]", nil, { id: :member_6, required: "required" }

  = label_tag :member_7
  = text_field_tag "member_names[]", nil, { id: :member_7, required: "required" }

  = label_tag :member_8
  = text_field_tag "member_names[]", nil, { id: :member_8, required: "required" }

  = submit_tag "はじめる！"